module.exports = {
    USER_CONNECTED: 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_CONNECTED',
    VERIFY_USER: 'VERIFY_USER',
    OTHER_DISCONNECTED: 'OTHER_DISCONNECTED',
    OTHER_SENT: 'OTHER_SENT',
    SELF_SENT: 'SELF_SENT',
};
